CatsProject/config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rental_requests
end

CatsProject/app/models/cat.rb
class Cat < ActiveRecord::Base
  include ActionView::Helpers::DateHelper

  CAT_COLORS = ["red", "orange", "yellow", "green", "blue" ,"indigo", "violet"]

  validates :birthdate, :color, :name, :sex, :description, presence: true
  validates :sex, length: { is: 1 }
  validates :color, inclusion: { in: CAT_COLORS }

  has_many :cat_rental_requests, dependent: :destroy,
  primary_key: :id,
  foreign_key: :cat_id,
  class_name: :CatRentalRequest


  def self.colors
    CAT_COLORS
  end

  def age
    time_ago_in_words(birthdate)
    # Date.today - birthdate
  end

end

CatsProject/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  STATUSES = ["PENDING","DENIED","APPROVED"]
  validates :start_date, :end_date, :cat_id, presence: true
  #validates :status, uniqueness: {scope: :cat_id}
  validates :status, inclusion: STATUSES
  before_create :default_status

  belongs_to :cat,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :Cat

  def self.all_statuses
    STATUSES
  end

  def overlapping_requests
    CatRentalRequest
      .where(cat_id: self.cat_id)
      .where('(start_date BETWEEN ? AND ? OR end_date BETWEEN ? AND ?) OR (start_date <= ? AND end_date >= ?)',
     start_date, end_date, start_date, end_date, start_date, end_date)
  end

  def approved_overlapping_requests
    overlapping_requests.where(status: "APPROVED")
  end

  private
  def default_status
    self.status = "PENDING" if self.status.nil?
  end
end

CatsProject/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

CatsProject/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    @cat_rental_request = CatRentalRequest.new
  end

  def index
    @cat_rental_requests = CatRentalRequest.all
  end

  def create
    @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)
    # fail
    if @cat_rental_request.save
      redirect_to cat_rental_requests_url
    else
      render :new
    end
  end

  def show
    @cat_rental_request = CatRentalRequest.find(params[:id])
  end

  def edit
    @cat_rental_request = CatRentalRequest.find(params[:id])
  end

  def update
    @cat_rental_request = CatRentalRequest.find(params[:id])
    @cat_rental_request.update_attributes(cat_rental_request_params)
    if @cat_rental_request.save
      render cat_rental_request_url
    else
      render :edit
    end
  end

  private
  def cat_rental_request_params
    params.require(:cat_rental_request).permit(:start_date, :end_date, :cat_id)
  end
end

CatsProject/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def new
    @cat = Cat.new
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cats_url
    else
      render :new
    end
  end

  def update
    @cat = Cat.find(params[:id])
    @cat.update_attributes(cat_params)
    if @cat.save
      redirect_to cats_url
    else
      render :edit
    end
  end

  private
  def cat_params
    params.require(:cat).permit(:birthdate, :color, :name, :description, :sex)
  end
end

CatsProject/app/helpers/application_helper.rb
module ApplicationHelper
end

CatsProject/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

CatsProject/app/helpers/cats_helper.rb
module CatsHelper
end

CatsProject/app/views/cat_rental_requests/_cat_rental_request.html.erb
<ul>
  <li><%= link_to "#{cat_rental_request.cat.name}", edit_cat_rental_request_url(cat_rental_request) %>
    <ul>
      <li><%= cat_rental_request.start_date %></li>
      <li><%= cat_rental_request.end_date %></li>
    </ul>
  </li>
</ul>

CatsProject/app/views/cat_rental_requests/_form.html.erb
<% if cat_rental_request.persisted? %>
  <% action, method, button_text = cat_rental_request_url(cat_rental_request), "PATCH", "Update Rental Request" %>
<% else %>
  <% action, method, button_text = cat_rental_requests_url, "POST", "Submit Cat Rental Request" %>
<% end %>
<form class="" action="<%=action%>" method="<%=method%>" id="cat_rental_request_submit_form">
  <input type="hidden" name="_method" value="<%= method %>">
  <label for="cat_rental_request_cat_id">Choose a Cat: </label>
  <select class="" name="cat_rental_request[cat_id]">
    <option disabled<% if cat_rental_request.cat_id.nil? %> selected <% end %>>Select a Cat</option>
    <% Cat.all.each do |cat| %>
      <option value="<%= cat.id %>" <% if cat_rental_request.cat_id == cat.id %> selected <% end %>><%= cat.name %></option>
    <% end %>
  </select>
  <br><br><br>
  <label for="cat_rental_request_start_date">Start Date: </label>
  <input type="date" name="cat_rental_request[start_date]" value="<%= cat_rental_request.start_date %>">
  <br><br><br>
  <label for="cat_rental_request_end_date">End Date: </label>
  <input type="date" name="cat_rental_request[end_date]" value="<%= cat_rental_request.end_date %>">
  <br><br>
  <input type="submit" form="cat_rental_request_submit_form" value="<%=button_text%>">
</form>
<br>
<%= button_to "Cancel", cat_rental_requests_url, method: :get %>

CatsProject/app/views/cat_rental_requests/edit.html.erb
<h1>Choose a Cat and Dates</h1>
<%= render "form", cat_rental_request: @cat_rental_request %>

CatsProject/app/views/cat_rental_requests/index.html.erb
<h1>All Cat Rental Requests</h1>
<%= render @cat_rental_requests %>

<%= link_to "new", new_cat_rental_request_url %>

CatsProject/app/views/cat_rental_requests/new.html.erb
<h1>Choose a Cat and Dates</h1>
<%= render "form", cat_rental_request: @cat_rental_request %>

CatsProject/app/views/cats/_cat.html.erb
<ul>
  <li><%= link_to cat.name, edit_cat_url(cat) %>
    <ul>
      <li><%= cat.birthdate %></li>
      <li><%= cat.age %></li>
      <li><%= cat.sex %></li>
      <li><%= cat.color %></li>
      <li><%= cat.description %></li>
    </ul>
  </li>
</ul>

CatsProject/app/views/cats/_form.html.erb
<% if cat.persisted? %>
  <% action, method, button_text = cat_url(cat), "PATCH", "Update Cat" %>
<% else %>
  <% action, method, button_text = cats_url, "POST", "Create New Cat" %>
<% end %>
<form action="<%= action %>" method="POST" id="cat_submit_form">
  <input type="hidden" name="_method" value="<%= method %>">

  <label for="cat_name">Name: </label>
  <input type="text" name="cat[name]" value="<%= cat.name %>" id="cat_name">
  <br><br><br>
  <label for="cat_sex">Sex: </label>
  <input type="radio" name="cat[sex]" value="F" id="cat_sex" <% if cat.sex == 'F' %> checked="true" <% end %> > Female
  <input type="radio" name="cat[sex]" value="M" id="cat_sex" <% if cat.sex == 'M' %> checked="true" <% end %> > Male
  <br><br><br>
  <label for="cat_color">Color: </label>
    <select name="cat[color]" id= "cat_color">
    <option disabled <% if cat.color.nil? %> selected="true" <% end %> >-- Select Color --</option>
    <% Cat.colors.each do |color| %>
      <option value="<%= color %>" <% if cat.color == color %> selected="true" <% end %> ><%= color %></option>
    <% end %>
  </select>
  <br><br><br>
  <label for="cat_birthdate">DOB: </label>
  <input type="date" name="cat[birthdate]" value="<%= cat.birthdate %>" id="cat_birthdate">
  <br><br><br>
  <label for="cat_description">Description: </label>
  <br>
  <textarea name="cat[description]" rows="8" cols="40" id="cat_description"><%= cat.description %></textarea>
  <br><br><br>
  <button type="submit" form="cat_submit_form" value="<%= button_text %>"><%= button_text %></button>
</form>
<%= button_to "Cancel", cats_url, method: :get %>

CatsProject/app/views/cats/edit.html.erb
<h1>Edit your cat!</h1>
<%= render "form", cat: @cat, submit_url: cat_url(@cat) %>

CatsProject/app/views/cats/index.html.erb
<h1>All Cats</h1>

<%= render @cats %>

CatsProject/app/views/cats/new.html.erb
<h1>Create a new cat!</h1>
<%= render "form", cat: @cat, submit_url: cats_url %>

CatsProject/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CatsProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>